name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t rentacat-web .

      - name: Run container for testing
        run: |
          docker run -d -p 8080:8080 --name testcontainer rentacat-web
          sleep 5
          curl -f http://localhost:8080 || exit 1

      - name: Stop container
        run: docker stop testcontainer
